function f=importfreqdata(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARAMETERTEST1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  PARAMETERTEST1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ParameterTest1 = importfile("C:\Users\Administrator\Desktop\9.15 Cell Growth\20190915_Parameter_Test_1.txt", [5, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Sep-2019 10:13:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", ".000000"];

% Specify column names and types
opts.VariableNames = ["LCRMeterSetting", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["LCRMeterSetting", "VarName16"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["LCRMeterSetting", "VarName16"], "ThousandsSeparator", ",");

% Import the data
ParameterTest1 = readtable(filename, opts);

%% Convert to output type
%%ParameterTest1 = table2array(ParameterTest1);
f=table2array(ParameterTest1(5,1:15));
end