function lnztot = lnztot(Q,a,ch,f,fc,kl,n,r,rs)
%LNZTOT
%    LNZTOT = LNZTOT(Q,A,CH,F,FC,KL,N,R,RS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Feb-2021 12:41:26

t2 = f.*pi.*2.0i;
lnztot = log(1.0./(kl+t2.*(ch+rs./(((f.*1i)./fc).^(-a+1.0)+1.0)))+1.0./(1.0./r+Q.*t2.^n));
